### ISSUE TITLE
[Документация] Взаимодействие с TypeScript

### ISSUE THREAD

**Issue by altwarg** [weyheyhey/effector-next#10]
@weyheyhey, подскажите, как взаимодействовать с Effector и Next.JS через этот пакет с использованием TypeScript? Указанные примеры в README и `/example` неактуальны для TypeScript, т.к. создаваемый `pageLoaded` является `Event` и в функцию `withStart` прокинут не может быть из-за несовместимости типов.

**Comment by weyheyhey** [comment]
@altwarg 
```
import { createEvent, PageContext } from "effector-next";

export const pageStarted = createEvent<PageContext>();
```

**Comment by altwarg** [comment]
Спасибо! Подскажите еще, пожалуйста, каким образом возможно использовать `withStart` с двумя Event? У меня есть необходимость обратиться к двум Store сразу и пробросить данные на страницу, соответственно, если я правильно понимаю, мне нужно обратиться к двум событиям (по одному на каждый Store), dispatch которых породит вызов fetch данных.

**Comment by weyheyhey** [comment]
Для этого необходимо воспользоваться апи самого эффектора:

```
import { forward, createEvent, PageContext } from "effector-next";

const eventOne = createEvent();
const eventTwo = createEvent();


const pageStarted = createEvent<PageContext>();

forward({
  from: pageStarted,
  to: [eventOne, eventTwo]
})
```

**Comment by altwarg** [comment]
В ходе применения effector в Next.JS возникло еще пару вопросов:
1. Какой из `forward` использовать -- импортируемый из `effector-next` или из `effector`? Возникает при импортировании из `effector-next` проблема с типами в `forward`, если пытаться создать связь между `Effect` и `Event`: приходится использовать `forward<any>`.
2. В Next.JS существует возможность в методе `getServerSideProps` вместо объекта с пропсами вернуть объект вида `{ notFound: true }`, что автоматически приведет к переводу на страницу 404. Каким образом данный механизм можно использовать с `withServer`?

**Comment by weyheyhey** [comment]
1. Все сущности нужно импортировать из пакета `effector-next`, `effector-next` по сути [реэкспортит эффектор](https://github.com/weyheyhey/effector-next/blob/master/src/index.ts#L5). Это необходимо для корректной работы ssr (что бы эвенты/эффект/сторы создавались в рамках одного домена). Явное указание `forward<any>` приходится указывать только для `forward` из `effector-next`?
2. В данный момент нет поддержки getServerSideProps и аналогичных ему методов.  Можно самому написать интеграцию по примеру автора эффектора https://www.patreon.com/posts/51754996

**Comment by altwarg** [comment]
Явное указание приходилось указывать для `forward` из `effector-next`, когда пытался связывать Event и Effect (один) в месте объявления. После вынесения в отдельный файл и импорта более подобного поведения не происходило.

В целом, насколько я понял, `getServerSideProps` реализуется посредством `withStart` метода. Печально, что нет возможности пробросить рендер встроенного компонента на 404, когда необходимо, еще до отрисовки компонента с `withStart`.
