### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by 7iomka** [weyheyhey/effector-next#2]
Привет.
Спасибо за пример!
Вижу что в обёртке юзается getInitialProps глобально для _app
Это делает невозможным билд по требованию - часть страниц как ssr, часто - статически оптимизированные (ssg) - согласно доке начиная с версии 9.3 они рекоммендуют юзать getServersideProps или getStaticProps на уровне декларации страницы, чтобы некст при сборке включил где это можно статическую оптимизацию.
Есть ли какая-то возможность реализовать код так чтоб не юзать глобально getInitialProps?
Спасибо.

**Comment by weyheyhey** [comment]
@7iomka в версии 1.0.0-alpha.0 реализован несколько другой подход для получения начального состояния при загрузке страницы. Теперь можно прикреплять стартовое событие с помощью ф-ции `witStart` непосредственно к странице, что позволяет выбирать между статической оптимизацией страницы и генерации страницы на сервере:

1. Если к странице прикреплен эвент, страница будет рендериться на сервере при каждом запросе:

```js
import * as React from "react";
import { withStart, createEvent } from "effector-next";

const pageLoaded = createEvent();
const enhance = withStart(pageLoaded);

function Page(){
  return <h1>server-side renders at runtime</h1>
}

export default enhance(Page);
```

2. Если к странице не прикреплять эвент, страница будет отрендерена в статический html

```js
import * as React from "react";

export default function Page(){
  return <h1>automatically rendered as static HTML</h1>
}
```

**Comment by 7iomka** [comment]
@weyheyhey, Благодарю за идеи.
У некста 3 мода для рендеринга страниц:

> 
> There are actually **3 rendering modes**, each of them has its own set of limitations 
> 1. **SSR** (doesn't have access to browser-related features (LocalStorage), but it does have access to request-related data (cookies, HTTP headers)) 
> 2. **Server during SSG** (doesn't have access to browser-related features (LocalStorage), nor to request-related data (cookies, localStorage, HTTP headers)) 
> 3. **Static rendering** (doesn't have access to server-related features (HTTP headers), but does have access to request-related data (cookie) and browser-related features (LocalStorage))

Я в эффекторе новичек.
С ридаксом (redux-toolkit)
https://github.com/zeit/next.js/tree/canary/examples/with-redux-toolkit
у меня есть понимание как должно быть оформлено взаимодействие со сторой не в ущерб статическому рендеру.
То есть сам факт подключения сторы к страницам никак не влияет на выбор типа рендеринга этой страницы. На него влияют лишь факторы наличия функций:
- getStatiProps - SSG (пропсы будут получены и прокинуты в компонент страницы в момент билда приложения)
- getServerSideProps - SSR(пропсы будут получены и прокинуты в компонент на стороне сервера всякий раз при заходе на страницу (как я понял))
- отсутствие любой из вышеуказанных функци - полная статика

Можете ли пояснить / показать пример юза / подключения сторы(или нескольких стор)
на примере примитивных парочки страниц на нексте чтобы я понял кейс как работать / подключить сторы не опасаясь за SSR проблемы? Паттерны проектирования с эффектором сильно отличаются от ридаксовских, и я понял +- как работать с эффектором  используя его лишь в csr режиме (вот пример подобного использования: https://github.com/Zilliqa/zilliqa-social-pay/tree/develop)
А когда речь заходит о том, чтоб работая со сторой(ами) в момент готовности страниц(ы) мы уже работали с актуальными данными в сторе(ах) - непонятно как это реализовать универсально.
Извиняюсь заранее если вопросы могут показаться глупыми)
Спасибо за любые идеи)

**Comment by weyheyhey** [comment]
@7iomka При подключении события к странице, у нее объявляется пустой getInitialProps, что выключает статическую оптимизацию некста для данной страницы. Простой пример работы можно посмотреть тут https://github.com/weyheyhey/effector-next/tree/master/example

**Comment by 7iomka** [comment]
> @7iomka При подключении события к странице, у нее объявляется пустой getInitialProps, что выключает статическую оптимизацию некста для данной страницы. Простой пример работы можно посмотреть тут https://github.com/weyheyhey/effector-next/tree/master/example

если на странице присутствует getServerSideProps, то прокидывание пустого getInitialProps выкинет ошибку. По этой причине в своем временном локальном форке вашего репозитория я закомментил декларацию getInitialProps.
Я считаю единственным выходом из данной ситуации - просто указать пользователю чтоб он подключал событие к странице которая заведомо использует getServerSideProps, иначе - не подключать.
Но остается открытым вопрос как юзать эффектор на статических страницах ( у который либо нет ни одной из функциий подготовки пропсов (static) или есть getStaticProps (ssg).
Как работать с такими страницами в плане использования эффектора?

**Comment by weyheyhey** [comment]
> если на странице присутствует getServerSideProps, то прокидывание пустого getInitialProps выкинет ошибку (типо нельзя юзать getInitialProps если указан getServerSideProps - юзайте что-то одно). По этой причине в своем временном локальном форке вашего репозитория я закомментил декларацию getInitialProps.

Лучше заранее определить для себя, каким образом происходит работа с состоянием приложения:
1. Состояние вынесено в отдельный слой и используется эффектор для его управления
2. Приложению не требуется отдельный слой (стейт менеджер), достаточно наличия getServerSideProps/getStaticProps + props drilling.

> Но остается открытым вопрос как юзать эффектор на статических страницах ( у который либо нет ни одной из функциий подготовки пропсов (static) или есть getStaticProps (ssg).
Как работать с такими страницами в плане использования эффектора?

Наличие `withStart` и  установленного getInitialProps у страницы говорит лишь о том, что необходимо при каждом запросе рендерить страницу на сервере, получая начальное состояние корневого домена. Никаких дополнительных ограничений это не накладывает. Вы все так же можете иметь на странице компоненты, взаимодействующие со сторами/эвентами/эффектами.

```
// components/some-component.js
import React from "react";
import { useEvent , useStore } from "effector-react";

import { $count, countIncreased } from "../models";

export function SomeComponent(){
  const count = useStore($count);
  const incCount = useEvent(countIncreased);

  return (
    <div>
      <h1>Current value: ${count}</h1>
      <button onClick={incCount}>Inc value</button>
    </div>
  );
}
```

```
// pages/index.js
import React from "react";

import { SomeComponent } from "../components";

export function SomePage(){
  return <SomeComponent/>;
}
```
