### ISSUE TITLE
Есть ли возможность использовать функцию Custom App вместо класса?

### ISSUE THREAD

**Issue by wwwtsv** [weyheyhey/effector-next#7]
В доке next.js можно определить кастомный компонент App как функцию. 
_https://nextjs.org/docs/advanced-features/custom-app_

**Код:**
```
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

const enhance = withHydrate();

export default enhance(MyApp);
```

но withHydrate ожидает тип typeof App.

Например, мне надо передать текущую тему в приложения из $store effector используя хуки effector useStore. В классовом компоненте мне этого не сделать.

Что можно сделать в такой ситуации?

**Comment by weyheyhey** [comment]
@wwwtsv  На текущий момент могу предложить следующее:

`
import App from "next/app";

const enhance = withHydrate();

class MyApp extends App {
  render() {
    const { pageProps, Component } = this.props;

    return (
      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <Component {...pageProps} />
      </ThemeProvider>
    );
  }
}

export default enhance(MyApp);
`

Ну или переопределить типы :

`
import App from "next/app";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

const enhance = withHydrate();

export default enhance(MyApp as unknown as typeof  App);
`

**Comment by wwwtsv** [comment]
Значит, получается, пока нет возможности достать начальное состояние из кастомного компонента App используя next-effector? То есть в таком случае лучше использовать, например, состояние App компонента для темы вместо эффектора?

**Comment by weyheyhey** [comment]
@wwwtsv есть возможность, в примере выше - кастомный компонент. Пока есть 1 ограничение - он должен наследоваться от App. Функциональный компонент использовать не получится.

**Comment by wwwtsv** [comment]
@weyheyhey Я имел ввиду получить состояние именно из модели effector. Возможно я чего то не понимаю, только знакомлюсь с эффектором, но обычно, я получаю состояние из effector при помощи хука next-effector 
`const store = useStore($store);`
А как в классовом компоненте то получить нач. состояние? Я же не могу в классовом компоненте хуки использовать.

**Comment by weyheyhey** [comment]
@wwwtsv Понял. Поскольку, да, в классовом компоненты хуки нельзя использовать, можно сделать обертку над провайдером темы и уже ее использовать в App

```
interface CustomThemeProviderProps {
  children:ReactNode;
}

function CustomThemeProvider({ children }:CustomThemeProviderProps){
  const theme = useStore($theme);
  
  return <ThemeProvider theme={theme}>{children}</ThemeProvider>
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <CustomThemeProvider>
      <GlobalStyles />
      <Component {...pageProps} />
    </CustomThemeProvider>
  );
}

const enhance = withHydrate();

export default enhance(MyApp);
```

**Comment by wwwtsv** [comment]
Понял, спасибо.
