### ISSUE TITLE
Вопрос: как выполнять getInitialProps после каждого перехода?

### ISSUE THREAD

**Issue by wwwtsv** [weyheyhey/effector-next#8]
Если я правильно понял после каждого перехода на другую страницу по умолчанию если мы определили в _app компоненте вот это 
```
 MyApp.getInitialProps = async (appContext) => {
   const appProps = await App.getInitialProps(appContext);

   return { ...appProps }
 }
```
Тогда при переходе на другую страницу, на стороне клиента при помощи `next/router` или `next/link` у нас всегда будет вызываться функция getInitialProps.

Как реализовать такую функциональность с effector-next? 
И будет ли это правильно практикой? 
Или лучше использовать разные эффекты для получения данных с api на стороне сервера в функции `withStart` и на стороне клиента просто в компоненте, например, в `useEffect`

Но было бы интересно все таки узнать можно ли использовать такой подход как вызов на стороне клиента getInitialProps с оберткой effector-next. Да, мы теряем возможности статической оптимизации в таком случае. Но все же.

**Comment by weyheyhey** [comment]
@wwwtsv getInitialProps в nextjs предназначен для получения начального состояния страницы/приложения. В биндингах effector-next, getInitialProps используется для получения начального состояния домена эффектора. Посколько не всегда те данные, что запрашиваются на сервере, нужно запрашивать и на клиенте, лучше явно  разделить запрос данных с сервера и запрос данных на клиенте. Сейчас получение данных на сервере завязано на  hoc  `withStart`, на клиенте же мы сами пишем код вида:

```
import { useEffect } from "react";
import { useEvent } from "effector-react";

import { effectorEvent } from "../model";

export default function SomePage() {
 const loadSomeData = useEvent(effectorEvent);
  
 useEffect(()=>{
   loadSomeData();
 }, [])
} 
```

Если нужно тригерить ивент при каждом переходе на страницу, можно сделать так (примерное решение):

```
// components/fetcher.js
import { useEffect } from "react";
import { useEvent } from "effector-react";
import { useRouter } from 'next/router';

import { fetchData } from "../model";

export function Fetcher() {
 const router = useRouter();
 const loadSomeData = useEvent(fetchData);
  
 useEffect(()=>{
   loadSomeData();
 }, [router. pathname, router.query])
} 
```

```
// pages/app.js
import App from "next/app";

import { Fetcher } from "../components";

export default class MyApp App {
  render(){
     const { Component, pageProps } = this.props;
     return (
      <>
         <Fetcher/>
         <Component {...pageProps} />
      </>
    )
  }
}

export default MyApp;
```
