### ISSUE TITLE
Why we need useEvent?

### ISSUE THREAD

**Issue by smenshikov** [weyheyhey/effector-next#9]
Я не очень понимаю необходимость использования useEvent. Может кто-то сможет рассказать суть проблемы которая пытается быть решенная через useEvent?

**Comment by weyheyhey** [comment]
@smenshikov Пару слов про это сказал создатель эффектора на недавнем [митапе](https://youtu.be/nLYc4PaTXYk?t=8289). Правда в рамках текущей реализации effector-next, провайдер со скоупом существует только на сервере, так что какой-либо необходимости в использовании use-event нету.
